spring: 
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: scott
    password: scott
  
  thymeleaf: 
    prefix: /webapp/WEB-INF
    suffix: .html
  
  